# Generated by Django 4.1.7 on 2023-03-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='iphone_x.jpg', upload_to='images'),
        ),
    ]
