# Generated by Django 4.1.7 on 2023-03-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='goods',
            new_name='good',
        ),
    ]
